
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fbRanks)
library(dplyr)
library(ggplot2)
library(igraph)
```

```{r}
setwd(getwd())
# Descarga de archivos
# https://www.football-data.co.uk/spainm.php
u1011 <- "https://www.football-data.co.uk/mmz4281/1011/SP1.csv"
u1112 <- "https://www.football-data.co.uk/mmz4281/1112/SP1.csv"
u1213 <- "https://www.football-data.co.uk/mmz4281/1213/SP1.csv"
u1314 <- "https://www.football-data.co.uk/mmz4281/1314/SP1.csv"
u1415 <- "https://www.football-data.co.uk/mmz4281/1415/SP1.csv"
u1516 <- "https://www.football-data.co.uk/mmz4281/1516/SP1.csv"
u1617 <- "https://www.football-data.co.uk/mmz4281/1617/SP1.csv"
u1718 <- "https://www.football-data.co.uk/mmz4281/1718/SP1.csv"
u1819 <- "https://www.football-data.co.uk/mmz4281/1819/SP1.csv"
#Notamos que el último data set tiene unn tratamiento distinto. Optamoms por tratarlo de maera indepediente.
#u1920 <- "https://www.football-data.co.uk/mmz4281/1920/SP1.csv"

download.file(url = u1011, destfile ="RawData/SP1-1011.csv", mode = "wb")
download.file(url = u1112, destfile ="RawData/SP1-1112.csv", mode = "wb")
download.file(url = u1213, destfile ="RawData/SP1-1213.csv", mode = "wb")
download.file(url = u1314, destfile ="RawData/SP1-1314.csv", mode = "wb")
download.file(url = u1415, destfile ="RawData/SP1-1415.csv", mode = "wb")
download.file(url = u1516, destfile ="RawData/SP1-1516.csv", mode = "wb")
download.file(url = u1617, destfile ="RawData/SP1-1617.csv", mode = "wb")
download.file(url = u1718, destfile ="RawData/SP1-1718.csv", mode = "wb")
download.file(url = u1819, destfile ="RawData/SP1-1819.csv", mode = "wb")
#download.file(url = u1920, destfile ="RawData/SP1-1920.csv", mode = "wb")
```

```{r}
setwd(getwd())
lista_datos <- lapply(paste("RawData/", list.files(path = "RawData"), sep = ""), read.csv)
```

```{r}
lista_datos <- lapply(lista_datos, select, Date:FTAG, BbMx.2.5:BbAv.2.5.1)
#Los formatos de fecha cambian en el último data set, por lo que lo hacemos a parte
lista_datos[1:8] <- lapply(lista_datos[1:8], mutate, Date = as.Date(Date, format = "%d/%m/%y"))
lista_datos[[9]] <- lista_datos[[9]] %>% mutate(Date = as.Date(Date, format = "%d/%m/%Y"))
```

```{r}
#Esto lo hacemos a parte porque se le da un tratamiento distinto al resto de los data sets.
u1920 <- "https://www.football-data.co.uk/mmz4281/1920/SP1.csv"
download.file(url = u1920, destfile ="RawData/SP1-1920.csv", mode = "wb")
d1920 <- read.csv("RawData/SP1-1920.csv")
d1920S <- select(d1920, Date:FTAG, Max.2.5:Avg.2.5.1, -Time)
d1920S <- mutate(d1920S, Date = as.Date(Date, format = "%d/%m/%Y"))
```

```{r}
#Utilizamos la función do.call para ahorrarnos varias líneas de código, aprovechando que tenemos los mayoría de los conjuntos de datos en una lista.
d1019S <- do.call(rbind, lista_datos)

#Renombramos las columnas
#Las especificaciones de las notas indican que se hacen apuestas 1X2; es decir, se apuesta sobre el equipo ganador y sobre los goles totales (como en este caso) (https://www.oddsshark.com/es/apuestas-deportivas/tipos-de-apuestas/apuestas-1x2)

#Las siguientes variables son para las cuotas de apuestas de goles totales:

#BbOU = Número de casas de apuestas de BetBrain utilizadas para calcular promedios y máximos de más/menos de 2,5 goles (goles totales)
#BbMx>2.5 = Máximo de Betbrain sobre 2.5 goles
#BbAv>2.5 = Promedio de Betbrain sobre 2.5 goles
#BbMx<2.5 = Betbrain máximo por debajo de 2.5 goles
#BbAv<2.5 = Promedio de Betbrain por debajo de 2.5 goles

#BetBrain es un sitio web donde se pueden obtener los momios de los equipos en partidos actuales y hacer apuestas en diferentes casas de apuestas

d1019S <- rename(d1019S,  Max.2.5.O = BbMx.2.5, 
                 Avg.2.5.O = BbAv.2.5, 
                 Max.2.5.U = BbMx.2.5.1,
                 Avg.2.5.U = BbAv.2.5.1)

d1920S <- rename(d1920S,  Max.2.5.O = Max.2.5, 
                 Avg.2.5.O = Avg.2.5, 
                 Max.2.5.U = Max.2.5.1,
                 Avg.2.5.U = Avg.2.5.1)
```

```{r}
# Ordenamos las columnas
d1019S <- select(d1019S, colnames(d1920S))
```

```{r}
# Unimos las observaciones
d1020S <- rbind(d1019S, d1920S)
```

```{r}
# Renombramos
d1020S <- rename(d1020S, Date = Date, Home.team = HomeTeam, 
                 Home.score = FTHG, Away.team = AwayTeam, Away.score = FTAG)
# Ordenamos columnas
data <- select(d1020S, Date, Home.team, Home.score, Away.team, Away.score:Avg.2.5.U) 
# Ahora ya tenemos un data frame que contiene todos los datos necesarios
```

```{r}
head(data, n = 2L); tail(data, n = 2L)
```

```{r}
# Data frames de partidos y equipos
md <- data %>% select(Date:Away.score)
#Guardamos el anterior data frame en unn archivo .csv
write.csv(md, "match.data.csv", row.names = FALSE)
df <- create.fbRanks.dataframes(scores.file = "match.data.csv")
teams <- df$teams
scores <- df$scores
```

```{r}
#utilizamos estas funciones solo para conocer la estructura/contenido de los nuevos datos.
head(teams, n = 2L)
dim(teams)
head(scores, n = 2L)
dim(scores)
```

```{r}
# Conjuntos iniciales de entrenamiento y de prueba

f <- scores$date # Fechas de partidos
fu <- unique(f) # Fechas sin repetición
Ym <- format(fu, "%Y-%m") # Meses y años
Ym <- unique(Ym) # Meses y años sin repetir
places <- which(Ym[15]==format(scores$date, "%Y-%m")) # Consideramos partidos del 15vo mes tomando en cuenta que el primer mes es 2010-08 para comenzar a ajustar el modelo
ffe <- scores$date[max(places)] # Fecha final conjunto de entrenamiento (el último partido se jugó en 2011-12-18)

# Ya que tenemos la fecha del último partido que se jugó en los primeros 15 meses (de acuerdo a las fechas del data set), ahora podemos tomar todos los partidos que se jugaron en los primeros 15 meses como nuestro conjunto de entrenamiento.
```

```{r}
# Consideraremos partidos de 15 meses para comenzar a ajustar el modelo. Así, nuestro primer conjunto de entrenamiento consiste de datos de partidos hasta el 2011-12-18
train <- scores %>% filter(date <= ffe)
test <- scores %>% filter(date > ffe)
```

```{r}
#Con esto podemos ver la descripción de los primeros y últimos partidos en los datos de entrenamiento y testeo.
head(train, n = 1); tail(train, n = 1)
head(test, n = 1); tail(test, n = 1)
```

```{r}
# Primer ajuste del modelo
#Para un mejor funcionamiento al entrenar y probar el primer modelo, tomamos las fechas de los encuentros únicos.
traindate <- unique(train$date)
testdate <- unique(test$date)

#Hacemos el modelo (una regresión poisson) para predecir el resultado de los partidos entre dos equipos de acuerdo a sus fuerza de ataque y defensa.

#Véase que al colocar scores = scores, estamos agregando toda la información que tenemos, es decir los partidos desde el año 2010 al 2020. Al asignar min.date y max.date, estamos limitado los datos que se van a considerar para entrenar la regresión poisson (en el predict) aunque seguimos teniendo guardados los partidos que sucedieron después del testdate.
ranks <- rank.teams(scores = scores, teams = teams, 
                    min.date = traindate[1], 
                    max.date = traindate[length(traindate)])
print(ranks)
```

```{r}
# Primera predicción en la primera fecha del 2012 (recordar que en ranks se tiene cuales partidos sucedieron)
pred <- predict(ranks, date = testdate[1])

#Separamos los datos de las predicciones
phs <- pred$scores$pred.home.score # predicted home score
pas <- pred$scores$pred.away.score # predicted away score
pht <- pred$scores$home.team # home team in predictions
pat <- pred$scores$away.team # away team in predictions

#Partidos reales: 2012-01-07
#scores %>% filter(date == as.Date("2012-01-07"))
#tibble(date = "2012-01-07", home.team = pht, home.score = phs, away.team= pat, away.score = pas)

#Podemos ver que no se predicen 2 de 5 partidos (el de Malaga vs Ath Madrid y Santander  vs Zaragoza).

#con el resto de partidos, podemos ver que no se predice con gran exactitud el número de goles ni tampoco con el equipo ganador en la mayoría de los casos.
```

```{r}
scores %>% filter(date == testdate[1])
```

```{r}
phs <- NULL; pas <- NULL; pht <- NULL; pat <- NULL
#Véase que varias veces se tiene que calcular esta instrucción dentro del ciclo y podríamos solo calcularlo una vez y luego acceder a uno de sus elementos.
unique_dates <- unique(scores$date)
#Con length(unique_dates)-170) estamos haciendo 1066 iteraciones, y básicamente con cada iteración estamos creando conjuntos de entrenamiento de 170 fechas (empezando en 2010-08-28) para predecir los partidos de los siguientes días. Por ejemplo, primero se utilizan los partidos entre 2010-08-28 (unique_dates[1]) a 2012-03-04 (unique_dates[170]) para predecir los partidos del día 2012-03-05 (unique_dates[170+1]).
for(i in 1:(length(unique_dates)-170)){
  ranks <- rank.teams(scores = scores, teams = teams, 
                      min.date = unique_dates[i], 
                      max.date = unique_dates[i+170-1], 
                      silent = TRUE,
                      time.weight.eta = 0.0005)
  #Véase que este objeto se va modificando varias veces, por lo que al ver pred en la consola, solo veremos el último ejecutado en este ciclo y no el ajuste de todas las iteraciones.
  
  #Véase que al final, se predice los resultados de la última fecha: 2020-07-19.
  pred <- predict(ranks, date = unique_dates[i+170],
                  silent = TRUE)
  
  #Ya que estamos prediciendo los partidos de 1 día, por cada iteración; phs, pas, pht y pat podrían no ser del mismo tamaño (el tamaño de cada vector es el mismo que el número de partidos por día).
  phs <- c(phs, pred$scores$pred.home.score) # predicted home score
  pas <- c(pas, pred$scores$pred.away.score) # predicted away score
  pht <- c(pht, pred$scores$home.team) # home team in predictions
  pat <- c(pat, pred$scores$away.team) # away team in predictions
}
```

```{r}
#Una manera más rápida de hacer lo anterior:
phs <- list(); pas <- list(); pht <- list(); pat <- list()
for(i in 1:(length(unique(scores$date))-170)){
  ranks <- rank.teams(scores = scores, teams = teams, 
                      min.date = unique(scores$date)[i], 
                      max.date = unique(scores$date)[i+170-1], 
                      silent = TRUE,
                      time.weight.eta = 0.0005)
  #Véase que este objeto se va modificando varias veces, por lo que al ver pred en la consola, solo veremos el último ejecutado en este ciclo y no el ajuste de todas las iteraciones.
  pred <- predict(ranks, date = unique(scores$date)[i+170],
                  silent = TRUE)
  
  phs[[i]] <- pred$scores$pred.home.score # predicted home score
  pas[[i]] <- pred$scores$pred.away.score # predicted away score
  pht[[i]] <- pred$scores$home.team # home team in predictions
  pat[[i]] <- pred$scores$away.team # away team in predictions
}
phs <- unlist(phs)
pas <- unlist(pas)
pht <- unlist(pht)
pat <- unlist(pat)
```
 
```{r}
# Eliminamos NA's
buenos <- !(is.na(phs) | is.na(pas)) # 
phs <- phs[buenos] # predicted home score
pas <- pas[buenos] # predicted away score
pht <- pht[buenos] # home team in predictions
pat <- pat[buenos] # away team in predictions
#Con lo siguiente, estamos tomando todos que se predijeron en cada uno de los ciclos anteriores (el primer bloque de fechas predice el día unique(scores$date)[171] = 2012-03-05)
momio <- data %>% filter(Date >= unique(scores$date)[171])
momio <- momio[buenos,] #Nos quedamos donde no haya Nulos en las predicciones.
# Estas dos medias nos "ayudan" a ver que equipos se tienen en las predicciones y los partidos reales.
mean(pht == momio$Home.team)
mean(pat == momio$Away.team)

#Lo siguiente da la proporción de partidos que se predijeron (phs + pas) y que sucedieron (momio$Home.score + momio$Away.score) con más de 2.5 goles
mean(phs + pas > 2.5 & momio$Home.score + momio$Away.score > 2.5)
#[1] 0.3295019
#Probabilidad de obtener más de 2.5 goles según el modelo y los datos: 0.3295019
#Lo siguiente da la proporción de partidos que se predijeron (phs + pas) y que sucedieron (momio$Home.score + momio$Away.score) con menos de 2.5 goles
mean(phs + pas < 2.5 & momio$Home.score + momio$Away.score < 2.5)
#[1] 0.2436143
#Guardamos los goles que se obtuvieron en los partidos a partir del 2012-03-05, tanto en los equipos locales como en los visitantes.
hs <- momio$Home.score
as <- momio$Away.score

#Recordar que las variables Max.2.5.O, Avg.2.5.O, Max.2.5.U, Avg.2.5.U están tomando 2.5 goles para las cuotas de las apuestas.
```
 
```{r}
#Recordar que nos importan 2.5 goles para las cuotas de las apuestas.

# Probabilidades condicionales
mean(phs + pas > 3) # proporción de partidos con más de tres goles según el modelo
#[1] 0.2784163
mean(hs + as > 2.5 & phs + pas > 3)/mean(phs + pas > 3) 
# probabilidad condicional estimada de ganar en over 2.5
#Es decir: la probabilidad de obtener más de 2.5 goles en un partido dado que el modelo me dijo que suceden más de 3 goles (es decir que pasen 2.5 cuando me dijo el modelo que pasarán 3) es 0.6479358. 
mean(phs + pas < 2.1) # proporción de partidos con menos de 2.1 goles según el modelo
#[1] 0.1701788
mean( hs + as < 2.5 & phs + pas < 2.1)/mean(phs + pas < 2.1) 
# probabilidad condicional estimada de ganar en under 2.5
# De manera similar, la probabilidad de obtener menos de 2.5 goles en el partido, dado que el modelo me dijo que sucederían menos de 2.1, es de 0.5891182
```


```{r}
data
```


```{r}
# Juegos con momios máximos (es decir, apuestas sobre el número de goles)
#cap: capital inicial
cap <- 50000; g <- NULL

#Es decir, se hacen tantas iteraciones como datos en phs (recordar que se tienen datos desde 2012-03-05 hasta 2020-07-19)
for(j in 1:length(phs)){
  #Hacemos dos apuestas sobre los juegos donde se predijeron más de 3 goles o menos de 2.1 goles. 0.64/(momio$Max.2.5.O[j]^-1) > 1 y 0.58/(momio$Max.2.5.U[j]^-1) > 1 nos ayudan a filtrar los partidos en los que las cuotas nos permitan obtener una ganancia mínima. 

  #Primera apuesta:
  #Si se predijeron más de 3 goles por partido y el 64% de la cuota máxima es mayor a 1 entonces apostamos:
  if(((phs[j] + pas[j]) > 3) & (0.64/(momio$Max.2.5.O[j]^-1) > 1)){
    #Checamos que se hayan obtenido más de 2.5 goles, en todo caso ganamos ...
    if((hs[j] + as[j]) > 2.5) cap <- cap + 1000*(momio$Max.2.5.O[j]-1)
    #Si no se obtuvieron esos goles, perdemos 1000 unidades monetarias.
    else cap <- cap - 1000
    g <- c(g, cap)
  }
  #Segunda apuesta:
  #Si se predijeron menos de 2.1 goles por partido y el 58% de la cuota máxima es mayor a 1 entonces apostamos:
  if(((phs[j] + pas[j]) < 2.1) & (0.58/(momio$Max.2.5.U[j]^-1) > 1)){
    #Checamos que se hayan obtenido meos de 2.5 goles, en todo caso ganamos ...
    if((hs[j] + as[j]) < 2.5) cap <- cap + 1000*(momio$Max.2.5.U[j]-1)
    #Si no se obtuvieron esos goles, perdemos 1000 unidades monetarias.
    else cap <- cap - 1000
    g <- c(g, cap)
  }
}

# Escenario con momios máximos
g <- data.frame(Num_Ap = 1:length(g), Capital = g)
p <- ggplot(g, aes(x=Num_Ap, y=Capital)) + geom_line( color="#FC471F") + geom_point() +
  labs(x = "Número de juego", 
       y = "Capital",
       title = "Realizando una secuencia de juegos") +
  theme(plot.title = element_text(size=12, hjust = 0.5, face = "bold"),
        axis.text.x = element_text(face = "bold", size = 10, colour = "black"),
        axis.text.y = element_text(face = "bold", size = 10, colour = "black"),
        panel.grid.major = element_line(colour = "gray77"), 
        panel.grid.minor = element_line(colour = "gray97"), 
        axis.text = element_text(colour = "gray82"), 
        panel.background = element_rect(fill = "gray97", linetype = "solid"), 
        plot.background = element_rect(colour = "aliceblue"))   
p
```

```{r}
# Escenario con momios promedio
cap <- 50000; g <- NULL

for(j in 1:length(phs)){
  if(((phs[j] + pas[j]) > 3) & (0.64/(momio$Avg.2.5.O[j]^-1) > 1)){
    if((hs[j] + as[j]) > 2.5) cap <- cap + 1000*(momio$Avg.2.5.O[j]-1)
    else cap <- cap - 1000
    g <- c(g, cap)
  }
  
  if(((phs[j] + pas[j]) < 2.1) & (0.58/(momio$Avg.2.5.U[j]^-1) > 1)){
    if((hs[j] + as[j]) < 2.5) cap <- cap + 1000*(momio$Avg.2.5.U[j]-1)
    else cap <- cap - 1000
    g <- c(g, cap)
  }
}

g <- data.frame(Num_Ap = 1:length(g), Capital = g)
p <- ggplot(g, aes(x=Num_Ap, y=Capital)) + geom_line( color="#FC471F") + 
  geom_point(size =.7) +
  labs(x = "Número de juego", 
       y = "Capital",
       title = "Realizando una secuencia de juegos") +
  theme(plot.title = element_text(size=12, hjust = 0.5, face = "bold"),
        axis.text.x = element_text(face = "bold", size = 10, colour = "black"),
        axis.text.y = element_text(face = "bold", size = 10, colour = "black"),
        panel.grid.major = element_line(colour = "gray77"), 
        panel.grid.minor = element_line(colour = "gray97"), 
        axis.text = element_text(colour = "gray82"), 
        panel.background = element_rect(fill = "gray97", linetype = "solid"), 
        plot.background = element_rect(colour = "aliceblue"))  
p
```
 
```{r}
local <- "Barcelona"
scores %>% filter(home.team == local) %>% 
  ggplot(aes(x = factor(c(sum(home.score), sum(away.score))))) + 
  facet_wrap("away.team") + 
  geom_bar()
```

```{r}
local <- "Barcelona"
scores %>% filter(home.team == local) %>% 
  ggplot(aes(x = home.score)) + 
  facet_wrap("away.team") + 
  geom_bar()
```

```{r}
scores
```

